### ISSUE TITLE
Invalid dimensions for plot on mobile device in landscape 

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/app#135]
See: https://community.openenergymonitor.org/t/octopus-agile-emoncms-app/11767/89

**Comment by whatsupskip** [comment]
I am seeing essentially the same error on Android when using Chrome to view the "Solar App" page. It happens if the phone is slightly rotated or rotated 90 degrees. This is for EmonCMS running locally on RPi on version low-write 10.2.1 & low-write 10.2.0. I don't believe the error was occurring on 10.1.13.

**Comment by glynhudson** [comment]
I've also noticed this, the issue effects most apps including MyElectric and MySolar PV

![Screenshot_20200408-004612](https://user-images.githubusercontent.com/758844/78729815-f3925280-7932-11ea-9dd2-c6d25cbaf575.png)

https://photos.app.goo.gl/FEaDynSYivoVPKDU8

**Comment by glynhudson** [comment]
Issue also effects the new version of emoncms.org apps 

![H5PwqaQS](https://user-images.githubusercontent.com/758844/78760077-87d2d880-7978-11ea-9318-8370ec409f5f.jpg)

**Comment by glynhudson** [comment]
Issue has been fixed https://github.com/emoncms/app/commit/f3bbb297b65b5a84cabf4e32cfd9074ce7807e91
