### ISSUE TITLE
Can gas and openevse be added in variant of myelectric2?

### ISSUE THREAD

**Issue by joverbee** [emoncms/app#44]
I recently obtained an emonpi system and added a hall sensor for a gas meter onto an emonth. This works nicely so far as i progress setting things up. I really like the zerocarbonbrittain comparison in myelectric2 and it would be very nice if also the share of my ev (openevse) and heating (gas) could be shown in the comparison. I am already shocked about how much energy is consumed in heating when expressed in kwh, as usually i only thought of the bill which is roughly comparable to the elektricity bill. 
Anyway, i am inclined to give it a try starting from the current code, unless someone has already moved in this direction or has arguments why this would be a bad idea (i never coded anything in php...but how hard can it be...lol)

**Comment by glynhudson** [comment]
Hi Jo,

Nice work getting up and running. Good to hear you have found the new
myelectric useful. No, it's not currently possible to add additional item
to the comparision stack. That's a good idea. Yes, feel free to submitt a
PR. Maybe also a good idea to discuss the idea with other users on the
community forum: https://community.openenergymonitor.org

On 26 Dec 2017 9:25 pm, "Jo Verbeeck" <notifications@github.com> wrote:

I recently obtained an emonpi system and added a hall sensor for a gas
meter onto an emonth. This works nicely so far as i progress setting things
up. I really like the zerocarbonbrittain comparison in myelectric2 and it
would be very nice if also the share of my ev (openevse) and heating (gas)
could be shown in the comparison. I am already shocked about how much
energy is consumed in heating when expressed in kwh, as usually i only
thought of the bill which is roughly comparable to the elektricity bill.
Anyway, i am inclined to give it a try starting from the current code,
unless someone has already moved in this direction or has arguments why
this would be a bad idea (i never coded anything in php...but how hard can
it be...lol)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/emoncms/app/issues/44>, or mute the thread
